### ISSUE TITLE
Unsuccessful installation on GNU/Linux Trisquel/Ubuntu distribution

### ISSUE THREAD

**Issue by iembry** [rorynolan/strex#3]
I have recently attempted to install your package on my GNU/Linux Trisquel 7.0/Ubuntu 14.04 distribution, but it was unsuccessful.

Below is the compilation process on my system:

    * installing *source* package ‘strex’ ...
    ** package ‘strex’ successfully unpacked and MD5 sums checked
    ** using staged installation
    ** libs
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG  -I"/library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG  -I"/library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c arg-match.cpp -o arg-match.o
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG  -I"/library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c interleave.cpp -o interleave.o
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG  -I"/library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c list-utils.cpp -o list-utils.o
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG  -I"/library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c split-by-nums.cpp -o split-by-nums.o
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG  -I"/library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c stod.cpp -o stod.o
    stod.cpp: In function ‘Rcpp::NumericVector char_to_num(Rcpp::CharacterVector, bool)’:
    stod.cpp:31:77: error: no matching function for call to ‘regex_replace(std::string&, std::regex&, const char [1])’
               std::string x_i_nocommas = std::regex_replace(x_i, comma_regex, "");
                                                                                 ^
    stod.cpp:31:77: note: candidates are:
    In file included from /usr/include/c++/4.8/regex:62:0,
                     from stod.cpp:4:
    /usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
         regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
         ^
    /usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
    stod.cpp:31:77: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
               std::string x_i_nocommas = std::regex_replace(x_i, comma_regex, "");
                                                                                 ^
    In file included from /usr/include/c++/4.8/regex:62:0,
                     from stod.cpp:4:
    /usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
         regex_replace(const basic_string<_Ch_type>& __s,
         ^
    /usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
    stod.cpp:31:77: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
               std::string x_i_nocommas = std::regex_replace(x_i, comma_regex, "");
                                                                                 ^
    make: *** [stod.o] Error 1
    ERROR: compilation failed for package ‘strex’
    * removing ‘/library/strex’
    * restoring previous ‘/library/strex’
	

Thank you.

**Comment by rorynolan** [comment]
Hi @iembry,
This failure is probably due to you having an old g++. Check your g++ version, it needs to be 4.9 or higher. If not, update g++. Alternatively, you could update ubuntu to 16.04 or later; that ships woth g++ 5. Please let me know if you are successful.
Thanks for your interest in strex. 
Rory

**Comment by muschellij2** [comment]
Got the same thing.  Maybe the system requirements are not just C++11 but something higher?

**Comment by rorynolan** [comment]
Hi @iembry and @muschellij2 
The new version (v1.1.0) of `strex` includes allowances for people with GCC < 4.9 and I can confirm it's working on my version of Ubuntu 14.04. Can you check it out for me? It's on CRAN so `install.packages("strex")` should work now.

**Comment by muschellij2** [comment]
Works for me now.  Had to upgrade processx before it worked (so may need a
version requirement upped)

Error : object ‘curl_fds’ is not exported by 'namespace:processx'
John

**Comment by rorynolan** [comment]
Thanks @muschellij2 
I've updated the dev version of `strex` to have the correct version of `processx`. It'll be on CRAN in about a week. 
@iembry I'll close this issue now but feel free to reopen if somehow installation is still failing for you.

**Comment by iembry** [comment]
@rorynolan I will try to install the newest CRAN version of `strex` and let you know if it works for me or not. Thank you.

**Comment by iembry** [comment]
@rorynolan  I was able to successfully install the latest CRAN version of `strex`. Thank you again.

**Comment by rorynolan** [comment]
Thanks for letting me know @iembry 
It's great to have people testing this in the wild!

**Comment by iembry** [comment]
@rorynolan   You're so welcome.
